[profile.release]
lto = true
opt-level = "z"
debug = false

[workspace]
members = [
    "eosio",
    "eosio_bytes",
    "eosio_derives",
    "eosio_macros",
    "eosio_sys",
    "eosio_types",
    "examples/eosio_token",
    "examples/hello",
    "examples/tictactoe"
]