[profile.release]
lto = true
opt-level = "z"
debug = false

[workspace]
members = [
    "eosio",
    "eosio_abi",
    "eosio_api",
    "eosio_macros",
    "eosio_sys",
    "eosio_types",
    "examples/hello",
    "examples/tic_tac_toe"
]