[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "eosio",
    "eosio_macros",
    "eosio_sys",
    "examples/addressbook",
    "examples/eosio_token",
    "examples/hello",
    "examples/hello_bare",
    "examples/tictactoe"
]
