version: "3"

services:

  nodeosd:
    hostname: nodeosd
    image: eosio/eos:v1.2.5
    entrypoint: /opt/eosio/bin/nodeosd.sh
    command: >
      --data-dir /opt/eosio/bin/data-dir
      --enable-stale-production
      --http-alias=nodeosd:8888
      --http-alias=127.0.0.1:8888
      --http-alias=localhost:8888
      --contracts-console
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    hostname: keosd
    image: eosio/eos:v1.2.5
    entrypoint: keosd
    command: >
      --wallet-dir /opt/eosio/bin/data-dir
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
      --unlock-timeout=99999999
    ports:
      - 8900:8900
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./target/wasm32-unknown-unknown/release:/mnt/dev/release:ro
      - ./examples:/mnt/dev/examples:ro
    links:
      - nodeosd
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true