[package]
name = "eosio_bytes"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
eosio_sys = { path = "../eosio_sys", version = "0.1" }