[package]
name = "eosio"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
license = "MIT/Apache-2.0"
description = "Library for building smart contracts on EOSIO blockchains"

[features]
default = ["std", "contract"]
std = []
alloc = []
contract = []
stdweb = []

[dependencies]
eosio_macros = { path = "../eosio_macros", version = "0.1" }
eosio_sys = { path = "../eosio_sys", version = "0.1" }
serde = "1.0"
serde_derive = "1.0"
