[package]
name = "eosio"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
license = "MIT/Apache-2.0"
description = "Library for building smart contracts on EOSIO blockchains"

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
eosio_macros = { path = "../eosio_macros", version = "0.1" }
eosio_sys = { path = "../eosio_sys", version = "0.1" }
